version: '3'
services:
  web:
    build:
      context: .
      args:
        - AUTHORIZED_IP_BUILDTIME=${AUTHORIZED_IP}
    ports:
      - "3333:3333"
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
